import type { CctvCamera } from './types';

export const UK_CURATED_CAMERAS: CctvCamera[] = [
  {
    id: 'ukc-cardiff-st-mary-street',
    lat: 51.4808,
    lng: -3.1791,
    name: 'St Mary Street',
    city: 'Cardiff',
    country: 'UK',
    external_url: 'https://www.skylinewebcams.com/en/webcam/united-kingdom/wales/cardiff/cardiff.html',
    source: 'UK Curated',
  },
  {
    id: 'ukc-edinburgh-waverley',
    lat: 55.9524,
    lng: -3.1892,
    name: 'Edinburgh City Centre',
    city: 'Edinburgh',
    country: 'UK',
    external_url: 'https://www.windfinder.com/webcams/edinburgh_scotland_unitedkingdom',
    source: 'UK Curated',
  },
  {
    id: 'ukc-belfast-city-hall',
    lat: 54.5964,
    lng: -5.9300,
    name: 'Belfast City Hall',
    city: 'Belfast',
    country: 'UK',
    external_url: 'https://www.myworldwebcams.com/ireland/belfast_city_hall.html',
    source: 'UK Curated',
  },
  {
    id: 'ukc-bristol-city',
    lat: 51.4545,
    lng: -2.5879,
    name: 'Bristol City',
    city: 'Bristol',
    country: 'UK',
    external_url: 'https://www.windfinder.com/webcams/bristol_england_unitedkingdom',
    source: 'UK Curated',
  },
  {
    id: 'ukc-liverpool-city',
    lat: 53.4084,
    lng: -2.9916,
    name: 'Liverpool Waterfront',
    city: 'Liverpool',
    country: 'UK',
    external_url: 'https://www.windfinder.com/webcams/liverpool_england_unitedkingdom',
    source: 'UK Curated',
  },
  {
    id: 'ukc-newcastle-city',
    lat: 54.9783,
    lng: -1.6178,
    name: 'Newcastle upon Tyne',
    city: 'Newcastle',
    country: 'UK',
    external_url: 'https://www.windfinder.com/webcams/newcastle',
    source: 'UK Curated',
  },
];
